/*
 * Choice.java
 *
 * Created on 6 giugno 2006, 23.35
 */

package gui;

import java.io.*;
import service.Filter;

/**
 *
 * @author  Angelo
 */
public class SelectSource extends javax.swing.JFrame {
    /** Creates new form Choice */
    
    private File source;
    private int flag = 0;
    
    @SuppressWarnings("static-access")
    public SelectSource(int mode) {
        initComponents();
        JFCDirectory.setFileSelectionMode(mode);
        if(JFCDirectory.getFileSelectionMode() == JFCDirectory.FILES_ONLY){
            JFCDirectory.setDialogTitle("Seleziona il Golden Standard");
            Filter filtro = new Filter("dot");
            JFCDirectory.setFileFilter(filtro);
            if(JFCDirectory.showOpenDialog(null) == JFCDirectory.APPROVE_OPTION){
                source = JFCDirectory.getSelectedFile();
                flag = 1;
            }
            else{
                this.dispose();
            }
        }
        else{
            if(JFCDirectory.showOpenDialog(null) == JFCDirectory.APPROVE_OPTION){
                source = JFCDirectory.getCurrentDirectory();
                flag = 1;
            }
            else{
                this.dispose();
            }
        }
        
    }

    public File getSource(){
        return this.source;
    }

    public int getFlag(){
        return this.flag;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFCDirectory = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        JFCDirectory.setDialogTitle("Seleziona la directory in cui salvare i file");
        JFCDirectory.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(JFCDirectory, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(JFCDirectory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 341, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-630)/2, (screenSize.height-375)/2, 630, 375);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser JFCDirectory;
    // End of variables declaration//GEN-END:variables
    
}
