/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StancaDialog.java
 *
 * Created on 26-dic-2010, 17.13.31
 */

package gui;

import java.util.LinkedList;
import java.util.List;
import javax.swing.JCheckBox;
import stancamanager.StancaValidator;

/**
 *
 * @author Peppe
 */
public class StancaDialog extends javax.swing.JDialog {
    private List<String>selectedOpts=new LinkedList<String>();
    private List<JCheckBox>checkBoxList=new LinkedList<JCheckBox>();
    private String publicIp;
    private String port;
    private String path;
    /** Creates new form StancaDialog */
    public StancaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        checkBoxList.add(jCbxOpt1);
        checkBoxList.add(jCbxOpt2);
        checkBoxList.add(jCbxOpt3);
        checkBoxList.add(jCbxOpt4);
        checkBoxList.add(jCbxOpt5);
        //checkBoxList.add(jCbxOpt6);
        checkBoxList.add(jCbxOpt7);
        //checkBoxList.add(jCbxOpt8);
        checkBoxList.add(jCbxOpt9);
        //checkBoxList.add(jCbxOpt10);
        checkBoxList.add(jCbxOpt11);
        checkBoxList.add(jCbxOpt13);        
        checkBoxList.add(jCbxOpt14);
        checkBoxList.add(jCbxOpt15);
        //checkBoxList.add(jCbxOpt16);
        //checkBoxList.add(jCbxOpt17);
        checkBoxList.add(jCbxOpt18);
        checkBoxList.add(jCbxOpt19);
        checkBoxList.add(jCbxOpt20);
        checkBoxList.add(jCbxOpt21);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCbxOpt1 = new javax.swing.JCheckBox();
        jCbxOpt2 = new javax.swing.JCheckBox();
        jCbxOpt3 = new javax.swing.JCheckBox();
        jCbxOpt4 = new javax.swing.JCheckBox();
        jCbxOpt5 = new javax.swing.JCheckBox();
        jCbxOpt7 = new javax.swing.JCheckBox();
        jCbxOpt6 = new javax.swing.JCheckBox();
        jCbxOpt8 = new javax.swing.JCheckBox();
        jCbxOpt9 = new javax.swing.JCheckBox();
        jCbxOpt10 = new javax.swing.JCheckBox();
        jCbxOpt11 = new javax.swing.JCheckBox();
        btOk = new javax.swing.JButton();
        jBxSelectAll = new javax.swing.JCheckBox();
        jCbxOpt13 = new javax.swing.JCheckBox();
        jCbxOpt14 = new javax.swing.JCheckBox();
        jCbxOpt15 = new javax.swing.JCheckBox();
        jCbxOpt16 = new javax.swing.JCheckBox();
        jCbxOpt17 = new javax.swing.JCheckBox();
        jCbxOpt18 = new javax.swing.JCheckBox();
        jCbxOpt19 = new javax.swing.JCheckBox();
        jCbxOpt20 = new javax.swing.JCheckBox();
        jCbxOpt21 = new javax.swing.JCheckBox();
        jTxPublicIp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxPort = new javax.swing.JTextField();
        btHelp = new javax.swing.JButton();
        jTxPath = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxUrl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Requisiti Legge Stanca");

        jCbxOpt1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt1.setText("Requisito 1");
        jCbxOpt1.setToolTipText("Il requisito accede al servizio http://validator.w3.org/");
        jCbxOpt1.setName("1"); // NOI18N
        jCbxOpt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt1ActionPerformed(evt);
            }
        });

        jCbxOpt2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt2.setText("Requisito 2");
        jCbxOpt2.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt2.setName("2"); // NOI18N
        jCbxOpt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt2ActionPerformed(evt);
            }
        });

        jCbxOpt3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt3.setText("Requisito 3");
        jCbxOpt3.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt3.setName("3"); // NOI18N

        jCbxOpt4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt4.setText("Requisito 4");
        jCbxOpt4.setToolTipText("Il requisito accede al servizio http://www.checkmycolours.com/");
        jCbxOpt4.setName("4_6"); // NOI18N
        jCbxOpt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt4ActionPerformed(evt);
            }
        });

        jCbxOpt5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt5.setText("Requisito 5");
        jCbxOpt5.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt5.setName("5"); // NOI18N

        jCbxOpt7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt7.setText("Requisito 7");
        jCbxOpt7.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt7.setName("7_8"); // NOI18N
        jCbxOpt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt7ActionPerformed(evt);
            }
        });

        jCbxOpt6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt6.setText("Requisito 6");
        jCbxOpt6.setToolTipText("Il requisito accede al servizio http://www.checkmycolours.com/");
        jCbxOpt6.setName("4_6"); // NOI18N
        jCbxOpt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt6ActionPerformed(evt);
            }
        });

        jCbxOpt8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt8.setText("Requisito 8");
        jCbxOpt8.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt8.setActionCommand("Criterio 8");
        jCbxOpt8.setName("7_8"); // NOI18N
        jCbxOpt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt8ActionPerformed(evt);
            }
        });

        jCbxOpt9.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt9.setText("Requisito 9");
        jCbxOpt9.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt9.setName("9_10"); // NOI18N
        jCbxOpt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt9ActionPerformed(evt);
            }
        });

        jCbxOpt10.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt10.setText("Requisito 10");
        jCbxOpt10.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt10.setName("9_10"); // NOI18N
        jCbxOpt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt10ActionPerformed(evt);
            }
        });

        jCbxOpt11.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt11.setText("Requisito 11");
        jCbxOpt11.setToolTipText("Il requisito accede al servizio http://jigsaw.w3.org/css-validator/");
        jCbxOpt11.setName("11"); // NOI18N

        btOk.setFont(new java.awt.Font("Tahoma", 0, 12));
        btOk.setText("Conferma");
        btOk.setToolTipText("C:\\TestRia\\java");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        jBxSelectAll.setFont(new java.awt.Font("Tahoma", 0, 12));
        jBxSelectAll.setText("Seleziona/Deseleziona tutti");
        jBxSelectAll.setName("jBxSelectAll"); // NOI18N
        jBxSelectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBxSelectAllActionPerformed(evt);
            }
        });

        jCbxOpt13.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt13.setText("Requisito 13");
        jCbxOpt13.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt13.setName("13"); // NOI18N

        jCbxOpt14.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt14.setText("Requisito 14");
        jCbxOpt14.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt14.setName("14"); // NOI18N

        jCbxOpt15.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt15.setText("Requisito 15");
        jCbxOpt15.setToolTipText("Il requisito accede al servizio http://tools.webaccessibile.org/test/check.aspx");
        jCbxOpt15.setName("15_16_17"); // NOI18N
        jCbxOpt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt15ActionPerformed(evt);
            }
        });

        jCbxOpt16.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt16.setText("Requisito 16");
        jCbxOpt16.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt16.setActionCommand("Criterio 15");
        jCbxOpt16.setName("15_16_17"); // NOI18N
        jCbxOpt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt16ActionPerformed(evt);
            }
        });

        jCbxOpt17.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt17.setText("Requisito 17");
        jCbxOpt17.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt17.setActionCommand("Criterio 15");
        jCbxOpt17.setName("15_16_17"); // NOI18N
        jCbxOpt17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbxOpt17ActionPerformed(evt);
            }
        });

        jCbxOpt18.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt18.setText("Requisito 18");
        jCbxOpt18.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt18.setActionCommand("Criterio 15");
        jCbxOpt18.setName("18"); // NOI18N

        jCbxOpt19.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt19.setText("Requisito 19");
        jCbxOpt19.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt19.setActionCommand("Criterio 15");
        jCbxOpt19.setName("19"); // NOI18N

        jCbxOpt20.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt20.setText("Requisito 20");
        jCbxOpt20.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt20.setActionCommand("Criterio 15");
        jCbxOpt20.setName("20"); // NOI18N

        jCbxOpt21.setFont(new java.awt.Font("Tahoma", 0, 12));
        jCbxOpt21.setText("Requisito 21");
        jCbxOpt21.setToolTipText("Il requisito non accede a nessun servizio esterno");
        jCbxOpt21.setActionCommand("Criterio 15");
        jCbxOpt21.setName("21"); // NOI18N

        jTxPublicIp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxPublicIp.setText("151.46.101.130");
        jTxPublicIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxPublicIpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("IP :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("PORT :");

        jTxPort.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTxPort.setText("80");
        jTxPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxPortActionPerformed(evt);
            }
        });

        btHelp.setText("Help ?");
        btHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHelpActionPerformed(evt);
            }
        });

        jTxPath.setFont(new java.awt.Font("Tahoma", 0, 12));
        jTxPath.setText("C:/TestRia/stancaReport");
        jTxPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxPathActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Salva file XML in :");

        jTxUrl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxUrl.setText("http://www.sinapsi.unina.it");
        jTxUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxUrlActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("URL :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBxSelectAll)
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(251, 251, 251)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCbxOpt16)
                                            .addComponent(jCbxOpt15)
                                            .addComponent(jCbxOpt14)
                                            .addComponent(jCbxOpt13)
                                            .addComponent(jCbxOpt11))
                                        .addComponent(btOk)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxUrl, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)))
                            .addContainerGap(11, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCbxOpt3)
                                .addComponent(jCbxOpt1)
                                .addComponent(jCbxOpt4)
                                .addComponent(jCbxOpt2)
                                .addComponent(jCbxOpt5))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCbxOpt10)
                                .addComponent(jCbxOpt9)
                                .addComponent(jCbxOpt8)
                                .addComponent(jCbxOpt6)
                                .addComponent(jCbxOpt7))
                            .addGap(156, 156, 156)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCbxOpt17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jCbxOpt18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jCbxOpt19, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(jCbxOpt20, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCbxOpt21))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(180, 180, 180)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxPort, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTxPublicIp, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(288, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTxPath, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTxPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTxPublicIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCbxOpt1)
                            .addComponent(jCbxOpt17)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jCbxOpt18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbxOpt19)
                                .addGap(3, 3, 3)
                                .addComponent(jCbxOpt20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbxOpt21))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jCbxOpt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbxOpt3)
                                .addGap(3, 3, 3)
                                .addComponent(jCbxOpt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCbxOpt5)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCbxOpt6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCbxOpt7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCbxOpt8)
                            .addGap(3, 3, 3)
                            .addComponent(jCbxOpt9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCbxOpt10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCbxOpt11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbxOpt13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbxOpt14)
                        .addGap(3, 3, 3)
                        .addComponent(jCbxOpt15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCbxOpt16)))
                .addGap(5, 5, 5)
                .addComponent(jBxSelectAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        for(JCheckBox controllo:checkBoxList){
            if(controllo.isSelected()){
                this.selectedOpts.add(controllo.getName());
            }
        }
        publicIp=this.jTxPublicIp.getText();
        port=this.jTxPort.getText();
        path=this.jTxPath.getText();

        this.setVisible(false);
    }//GEN-LAST:event_btOkActionPerformed

    private void jCbxOpt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCbxOpt2ActionPerformed

    private void jBxSelectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBxSelectAllActionPerformed
        // TODO add your handling code here:
        for(JCheckBox controllo:checkBoxList){
                controllo.setSelected(jBxSelectAll.isSelected());        
        }
        jCbxOpt6.setSelected((jBxSelectAll.isSelected()));
        jCbxOpt8.setSelected((jBxSelectAll.isSelected()));
        jCbxOpt10.setSelected((jBxSelectAll.isSelected()));
        jCbxOpt16.setSelected((jBxSelectAll.isSelected()));
        jCbxOpt17.setSelected((jBxSelectAll.isSelected()));
    }//GEN-LAST:event_jBxSelectAllActionPerformed

    private void jCbxOpt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt8ActionPerformed
        jCbxOpt7.setSelected(jCbxOpt8.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt8ActionPerformed

    private void jTxPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxPortActionPerformed

    private void jCbxOpt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt1ActionPerformed

    private void jCbxOpt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt4ActionPerformed
       // TODO add your handling code here:
        jCbxOpt6.setSelected(jCbxOpt4.isSelected());
        
    }//GEN-LAST:event_jCbxOpt4ActionPerformed

    private void jCbxOpt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt6ActionPerformed
       // TODO add your handling code here:
       jCbxOpt4.setSelected(jCbxOpt6.isSelected());
        
    }//GEN-LAST:event_jCbxOpt6ActionPerformed

    private void jCbxOpt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt7ActionPerformed
        jCbxOpt8.setSelected(jCbxOpt7.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt7ActionPerformed

    private void jCbxOpt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt9ActionPerformed
        jCbxOpt10.setSelected(jCbxOpt9.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt9ActionPerformed

    private void jCbxOpt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt10ActionPerformed
        jCbxOpt9.setSelected(jCbxOpt10.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt10ActionPerformed

    private void jCbxOpt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt15ActionPerformed
        jCbxOpt16.setSelected(jCbxOpt15.isSelected());
        jCbxOpt17.setSelected(jCbxOpt15.isSelected());

        // TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt15ActionPerformed

    private void jCbxOpt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt16ActionPerformed
        jCbxOpt15.setSelected(jCbxOpt16.isSelected());
        jCbxOpt17.setSelected(jCbxOpt16.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt16ActionPerformed

    private void jCbxOpt17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbxOpt17ActionPerformed
        jCbxOpt15.setSelected(jCbxOpt17.isSelected());
        jCbxOpt16.setSelected(jCbxOpt17.isSelected());// TODO add your handling code here:
    }//GEN-LAST:event_jCbxOpt17ActionPerformed

    private void btHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHelpActionPerformed
        // TODO add your handling code here:

        try {           
            String[] cmd = new String[4];
            cmd[0] = "cmd.exe";
            cmd[1] = "/C";
            cmd[2] = "start";
            cmd[3] = "http://it.wikipedia.org/wiki/Legge_Stanca#Elenco_dei_requisiti_di_accessibilit.C3.A0_per_i_siti_Internet_.28decreto_ministeriale_dell.E2.80.998_luglio_2005.29";
            Process p = Runtime.getRuntime().exec(cmd);
        }
        catch(Exception e) {
            System.out.println("Impossible to run Firefox.");
        }

    }//GEN-LAST:event_btHelpActionPerformed

    private void jTxPublicIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxPublicIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxPublicIpActionPerformed

    private void jTxPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxPathActionPerformed

    private void jTxUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxUrlActionPerformed

    public List<String> getSelectedOpts() {
        return selectedOpts;
    }

    public String getPort() {
        return port;
    }

    public String getPublicIp() {
        return publicIp;
    }

    /**
    * @param args the command line arguments
    */


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StancaDialog dialog = new StancaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHelp;
    private javax.swing.JButton btOk;
    private javax.swing.JCheckBox jBxSelectAll;
    private javax.swing.JCheckBox jCbxOpt1;
    private javax.swing.JCheckBox jCbxOpt10;
    private javax.swing.JCheckBox jCbxOpt11;
    private javax.swing.JCheckBox jCbxOpt13;
    private javax.swing.JCheckBox jCbxOpt14;
    private javax.swing.JCheckBox jCbxOpt15;
    private javax.swing.JCheckBox jCbxOpt16;
    private javax.swing.JCheckBox jCbxOpt17;
    private javax.swing.JCheckBox jCbxOpt18;
    private javax.swing.JCheckBox jCbxOpt19;
    private javax.swing.JCheckBox jCbxOpt2;
    private javax.swing.JCheckBox jCbxOpt20;
    private javax.swing.JCheckBox jCbxOpt21;
    private javax.swing.JCheckBox jCbxOpt3;
    private javax.swing.JCheckBox jCbxOpt4;
    private javax.swing.JCheckBox jCbxOpt5;
    private javax.swing.JCheckBox jCbxOpt6;
    private javax.swing.JCheckBox jCbxOpt7;
    private javax.swing.JCheckBox jCbxOpt8;
    private javax.swing.JCheckBox jCbxOpt9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField jTxPath;
    private javax.swing.JTextField jTxPort;
    private javax.swing.JTextField jTxPublicIp;
    public javax.swing.JTextField jTxUrl;
    // End of variables declaration//GEN-END:variables

}
